/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ocp.day18;

/**
 *
 * @author student
 */
public class LottoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LottoJFrame
     */
    public LottoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lotto_title = new javax.swing.JLabel();
        lotto_box = new javax.swing.JComboBox<>();
        lotto_Button = new javax.swing.JButton();
        lotto_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("樂透電腦選號");

        lotto_title.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        lotto_title.setForeground(new java.awt.Color(255, 51, 51));
        lotto_title.setText("樂透");

        lotto_box.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        lotto_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "金彩539", "4星彩" }));
        lotto_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotto_boxActionPerformed(evt);
            }
        });

        lotto_Button.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        lotto_Button.setText("選號");
        lotto_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotto_ButtonActionPerformed(evt);
            }
        });

        lotto_label.setFont(new java.awt.Font("微軟正黑體", 0, 30)); // NOI18N
        lotto_label.setForeground(new java.awt.Color(102, 51, 255));
        lotto_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotto_label.setText("00 00 00 00 00 00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lotto_label, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lotto_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lotto_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lotto_Button)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lotto_Button)
                    .addComponent(lotto_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotto_title))
                .addGap(18, 18, 18)
                .addComponent(lotto_label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotto_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotto_ButtonActionPerformed
        //System.out.println(lotto_box.getSelectedIndex());//0         1 
        //System.out.println(lotto_box.getSelectedItem());//金彩539   4星彩
        int idx = lotto_box.getSelectedIndex();
        switch (idx) {
            case 0:
                lotto_label.setText(LottoService.get539().toString().replace('[', ' ').replace(']', ' ').trim());
                break;
            case 1:
                lotto_label.setText(LottoService.get4Stars().toString());
                break;
        }
    }//GEN-LAST:event_lotto_ButtonActionPerformed

    private void lotto_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotto_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotto_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lotto_Button;
    private javax.swing.JComboBox<String> lotto_box;
    private javax.swing.JLabel lotto_label;
    private javax.swing.JLabel lotto_title;
    // End of variables declaration//GEN-END:variables
}
